# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: meteoServer.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11meteoServer.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"T\n\x0cRawMeteoData\x12\n\n\x02id\x18\x01 \x01(\t\x12\x13\n\x0btemperature\x18\x02 \x01(\x02\x12\x10\n\x08humidity\x18\x03 \x01(\x02\x12\x11\n\ttimestamp\x18\x04 \x01(\x03\">\n\x10RawPollutionData\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0b\n\x03\x63o2\x18\x02 \x01(\x02\x12\x11\n\ttimestamp\x18\x03 \x01(\x03\":\n\x0fWellnessResults\x12\x0c\n\x04time\x18\x01 \x01(\x01\x12\x0b\n\x03\x61vg\x18\x02 \x01(\x02\x12\x0c\n\x04\x64\x65sv\x18\x03 \x01(\x02\";\n\x10PollutionResults\x12\x0c\n\x04time\x18\x01 \x01(\x01\x12\x0b\n\x03\x61vg\x18\x02 \x01(\x02\x12\x0c\n\x04\x64\x65sv\x18\x03 \x01(\x02\"c\n\x07Results\x12*\n\x10wellness_results\x18\x01 \x01(\x0b\x32\x10.WellnessResults\x12,\n\x11pollution_results\x18\x02 \x01(\x0b\x32\x11.PollutionResults2\x91\x01\n\x13LoadBalancerService\x12\x38\n\rSendMeteoData\x12\r.RawMeteoData\x1a\x16.google.protobuf.Empty\"\x00\x12@\n\x11SendPollutionData\x12\x11.RawPollutionData\x1a\x16.google.protobuf.Empty\"\x00\x32\x92\x01\n\x0eProcessService\x12;\n\x10ProcessMeteoData\x12\r.RawMeteoData\x1a\x16.google.protobuf.Empty\"\x00\x12\x43\n\x14ProcessPollutionData\x12\x11.RawPollutionData\x1a\x16.google.protobuf.Empty\"\x00\x32\x44\n\x0fTerminalService\x12\x31\n\x0bSendResults\x12\x08.Results\x1a\x16.google.protobuf.Empty\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'meteoServer_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _RAWMETEODATA._serialized_start=83
  _RAWMETEODATA._serialized_end=167
  _RAWPOLLUTIONDATA._serialized_start=169
  _RAWPOLLUTIONDATA._serialized_end=231
  _WELLNESSRESULTS._serialized_start=233
  _WELLNESSRESULTS._serialized_end=291
  _POLLUTIONRESULTS._serialized_start=293
  _POLLUTIONRESULTS._serialized_end=352
  _RESULTS._serialized_start=354
  _RESULTS._serialized_end=453
  _LOADBALANCERSERVICE._serialized_start=456
  _LOADBALANCERSERVICE._serialized_end=601
  _PROCESSSERVICE._serialized_start=604
  _PROCESSSERVICE._serialized_end=750
  _TERMINALSERVICE._serialized_start=752
  _TERMINALSERVICE._serialized_end=820
# @@protoc_insertion_point(module_scope)
